/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zipkinCore_CONSTANTS_H
#define zipkinCore_CONSTANTS_H

#include "zipkinCore_types.h"



class zipkinCoreConstants {
 public:
  zipkinCoreConstants();

  std::string CLIENT_SEND;
  std::string CLIENT_RECV;
  std::string SERVER_SEND;
  std::string SERVER_RECV;
  std::string WIRE_SEND;
  std::string WIRE_RECV;
  std::string CLIENT_SEND_FRAGMENT;
  std::string CLIENT_RECV_FRAGMENT;
  std::string SERVER_SEND_FRAGMENT;
  std::string SERVER_RECV_FRAGMENT;
  std::string HTTP_HOST;
  std::string HTTP_METHOD;
  std::string HTTP_PATH;
  std::string HTTP_URL;
  std::string HTTP_STATUS_CODE;
  std::string HTTP_REQUEST_SIZE;
  std::string HTTP_RESPONSE_SIZE;
  std::string LOCAL_COMPONENT;
  std::string CLIENT_ADDR;
  std::string SERVER_ADDR;
};

extern const zipkinCoreConstants g_zipkinCore_constants;



#endif
